ecmwf/earthkit-data

- environment.yml
Conda "nags" users to add pip to environment.yml if using pip to install dependencies alongside conda packages.
```
$ mamba env create -f environment.yml
Retrieving notices: ...working... done
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```
> updated environment.yml with explicit pip

- .github/workflows/notify_new_pr.yml
So action triggers when a PR is opened by a contributor without write access to the repo.
> Switch notify_new_pr trigger to pull_request_target

- docs/requirements.txt
We need urllib3<2.0.0 on read the docs otherwise the builds fail due to the incompatibility between requests and urllib3 . See: https://github.com/psf/requests/issues/6432
> Limit urllib3 version for read the docs builds

- .readthedocs.yml
- docs/requirements.txt
Hello, urllib3 maintainer here :wave:
You don't need to pin urllib3 just to get Read the Docs working.
> Bump Read the Docs OS to use urllib3 2.0

- earthkit/data/readers/netcdf.py
- tests/readers/test_netcdf_reader.py
`standard_name` is expected to be of type string, e.g.
https://github.com/ecmwf/earthkit-data/blob/68d755906d8ce15c214345e07539b7a4e9af4b0f/earthkit/data/readers/netcdf.py#L307
this PR is related to https://github.com/ecmwf/earthkit-data/issues/62, which is for solving a bug with the `standard_name` attribute in a netcdf coordinates data array
note that (for consistency) the PR includes updating `axis` and `long_name` to be empty string also
> bugfix netcdf.py

- =
- environment.yml
- setup.cfg
* add python-eccodes as a direct dependency in setup.cfg (previously it was installed indirectly by cfgrib)
* set a  minimum version for it (it is required because earthkit-data uses the high level python interface, which is a newer development)
> Add python eccodes as a direct dependency with a minimum version

- docs/api.rst
- docs/conf.py
- earthkit/data/readers/grib/codes.py
- earthkit/data/readers/grib/fieldlist.py
- earthkit/data/readers/netcdf.py
- earthkit/data/sources/multi.py
- earthkit/data/utils/bbox.py
- tests/grib/test_grib_contents.py
- tests/readers/test_grib_reader.py
- tests/readers/test_netcdf_reader.py
- tests/utils/test_bbox.py
This PR alters the way the `bounding_box` method used on a `FieldList` in line with the internal discussions regarding the FieldList API.  It also changes some of the method names of `BoundingBox`. The outcome is summarised below:
- the `bounding_box` method on a FieldList returns a list of `BoundingBox` objects (one per field, both for GRIB and NetCDF)
- `BoundingBox`  has a classmethod `union` generating the union of the input list of `BoundingBox` objects
- `BoundingBox`  has an instance method `union_with` generating the union with another object
```python
bb_list = ds.bounding_box()
bb = BoundingBox.union(bb_list)
bb1 = BoundinBox(...)
bb2 = BoundingBox(...)
bb = bb1.union_with(bb2)
```
> Return list of BoundingBox objects on a FieldList

- docs/examples/grib_lat_lon_value.ipynb
- docs/examples/grib_metadata.ipynb
- earthkit/data/readers/grib/fieldlist.py
- tests/grib/test_grib_contents.py
The `data()` method only existed on a field. This PR implements it on a fieldlist too.
Example:
> Add data method to fieldlist

- docs/examples/grib_lat_lon_value.ipynb
- earthkit/data/core/fieldlist.py
- tests/grib/test_grib_values.py
The `data()` method on a Field or FieldList previously returned a tuple. This PR changes the return type to ndarray.
> Change return type in data method to ndarray

- earthkit/data/utils/module_inputs_wrapper.py
types is better choice than ast. ast does not create a clean Module and causes overwriting of methods.
> Fix for module imports

- earthkit/data/sources/numpy_list.py
- earthkit/data/writers/grib.py
- tests/sources/test_numpy_list.py
When we use `save` on a NumpyFieldLists it will write np.nan-s as missing values into the resulting grib data.
> Write missing values to grib output

- earthkit/data/readers/netcdf.py
- earthkit/data/wrappers/xarray.py
- tests/readers/test_netcdf_reader.py
- tests/wrappers/test_xarray.py
The scanning for fields in a NetCDF fieldlist is now delayed until the fields are actually needed.
```python
ds = from_source("file", earthkit_examples_file("test.nc"))
print(len(ds))
```
> Implement lazy fieldlist scanning for NetCDF data

- earthkit/data/readers/netcdf.py
- tests/netcdf/test_netcdf_output.py
- tests/sources/test_url.py
write method added to NetCDFFieldList method, simply redirect to the to_netCDF method.
> 194 write method added to NetCDFFieldList method

- earthkit/data/core/constants.py
- earthkit/data/geo/__init__.py
- earthkit/data/geo/distance.py
- tests/geo/test_geo.py
First implementation.
See the documentation in the `geo/distance.py` code.
This is a working example to extract time series for a given point:
```python
from earthkit.data import from_source
from earthkit.data.geo import nearest_point_haversine
ds = from_source("file", "tests/data/t_time_series.grib").sel(param="t")
latlon = ds.to_latlon()
lat = latlon["lat"]
lon = latlon["lon"]
p_ref = (51.45, -0.97)
idx = nearest_point_haversine(p_ref, (lat, lon))
```
12
```python
ds.values[:,idx]
```
array([280.44058228, 280.31297302, 280.2789917 , 280.08499146,
276.38993835])
> WIP: Implement haversine nearest point method

- earthkit/data/readers/grib/metadata.py
- tests/core/test_metadata.py
- tests/grib/test_grib_metadata.py
- tests/numpy_fs/test_numpy_fs_metadata.py
> Fix failing grib metadata tests

- earthkit/data/geo/distance.py
- tests/geo/test_geo.py
`geo.nearest_point_haversine()` now returns a tuple of `(index, distance)`.
```python
>>> from earthkit.data.geo import nearest_point_haversine
>>> p_ref = (51.45, -0.97)
>>> p_lat = [44.49, 50.73, 50.1]
>>> p_lon = [11.34, 7.90, -8.1]
>>> nearest_point_haversine(p_ref, (p_lat, p_lon))
(2, 523115.8314777661)
```
> Return index distance tuple in nearest_point_haversine

- earthkit/data/wrappers/pandas.py
- pytest.ini
- tests/readers/test_geojson_reader.py
Current implementation results in failed tests if the underlying installation of PROJ is not compatible.
This change attaches a marker to the test such that it can be omitted by the user.
The environments used by the CI tests do not have this issue, so it is not necessary to omit the test for the GH actions.
Also included is the assignment of NaN values to the boundingbox such that the attributes exist, they are just unknown, this would allow users to set by hand if desired.
> handle bad installations of PROJ

- docs/api.rst
- docs/skip_api_rules.py
- earthkit/data/core/fieldlist.py
- earthkit/data/readers/grib/__init__.py
- earthkit/data/readers/grib/codes.py
- earthkit/data/readers/grib/xarray.py
- earthkit/data/readers/netcdf.py
- earthkit/data/sources/numpy_list.py
- earthkit/data/sources/stream.py
- tests/grib/test_grib_stream.py
- tests/numpy_fs/numpy_fs_fixtures.py
- tests/numpy_fs/test_numpy_fs.py
This PR adds the `to_decoded` method to fieldlists. It can convert a fieldlist into a NumpyFieldList in such a way that all the values will be stored as a single numpy array.
> Add to_decoded method to fieldlist

- earthkit/data/core/fieldlist.py
- earthkit/data/sources/memory.py
- earthkit/data/sources/numpy_list.py
- earthkit/data/sources/stream.py
- tests/grib/test_grib_stream.py
- tests/numpy_fs/numpy_fs_fixtures.py
- tests/numpy_fs/test_numpy_fs.py
This PR replaces the recently added `to_decoded()` method on a `FieldList` with the more generic `to_fieldlist()`. The new method provides a means to convert one `FieldList` into another one using a different `backend`.
> Implement a generic to_fieldlist method instead of to_decoded

- .gitignore
- earthkit/data/core/fieldlist.py
- earthkit/data/core/index.py
- earthkit/data/readers/netcdf.py
- tests/grib/test_grib_inidces.py
- tests/indexing/test_indexing_db.py
- tests/sources/test_cds.py
> Fix indices() on fieldlist filtered with sel()

- docs/examples.rst
- docs/examples/fdb.ipynb
- docs/examples/grib_fdb_write.ipynb
- docs/examples/grib_from_stream.ipynb
- docs/examples/grib_url.ipynb
- docs/examples/grib_url_stream.ipynb
- docs/guide/sources.rst
- earthkit/data/readers/__init__.py
- earthkit/data/readers/grib/__init__.py
- earthkit/data/readers/grib/memory.py
- earthkit/data/sources/stream.py
- earthkit/data/sources/url.py
- earthkit/data/utils/__init__.py
- tests/grib/test_grib_stream.py
- tests/grib/test_grib_url_stream.py
This PR enables using GRIB data from a URL or multiple URLs as a stream.
```python
import earthkit.data
ds = earthkit.data.from_source("url",
["https://get.ecmwf.int/repository/test-data/earthkit-data/examples/test.grib",
"https://get.ecmwf.int/repository/test-data/earthkit-data/examples/test4.grib"], 
stream=True, batch_size=3)
for f in ds:
print(type(f))
print(f"len={len(f)}")
for g in f:
print(f" {g}")
```
```
<class 'earthkit.data.readers.grib.memory.GribFieldListInMemory'>
len=3
GribField(2t,None,20200513,1200,0,0)
GribField(msl,None,20200513,1200,0,0)
GribField(t,500,20070101,1200,0,0)
<class 'earthkit.data.readers.grib.memory.GribFieldListInMemory'>
len=3
GribField(z,500,20070101,1200,0,0)
GribField(t,850,20070101,1200,0,0)
GribField(z,850,20070101,1200,0,0)
```
Example: …
> Enable using url source as a stream

- earthkit/data/core/__init__.py
- earthkit/data/core/fieldlist.py
- earthkit/data/readers/__init__.py
- earthkit/data/readers/directory.py
- earthkit/data/readers/grib/codes.py
- earthkit/data/readers/grib/output.py
- earthkit/data/sources/file.py
- earthkit/data/sources/memory.py
- earthkit/data/sources/multi.py
- earthkit/data/sources/numpy_list.py
- earthkit/data/writers/grib.py
- setup.cfg
- tests/grib/test_grib_output.py
- tests/numpy_fs/test_numpy_fs_write.py
Fixes #274 
Previously, when writing a `NumpyFieldList` the `generatingProcessIdentifier` ecCodes GRIB key was always set to 255 (internally) in the output.
With this PR this key is not set implicitly but must be set explicitly in `Metadata.override()`. E.g.:
```python
md = ds[0].metadata().override(shortName="msl", generatingProcessIdentifier=255)
r = FieldList.from_numpy(ds[0].values, md)
r.save("my_data.grib")
```
> Do not implicitly set generatingProcessIdentifier when writing GRIB data

- earthkit/data/sources/multi_url.py
- earthkit/data/sources/stream.py
- earthkit/data/sources/url.py
- earthkit/data/utils/url.py
- tests/grib/test_grib_url.py
- tests/grib/test_grib_url_stream.py
- tests/sources/test_url.py
This PR makes parts (only single parts) work for url streams:
```python
ds = from_source(
"url",
"https://get.ecmwf.int/repository/test-data/earthkit-data/examples/test6.grib",
parts=[(0, 480)],
stream=True,
)
for f in ds:
print(f)
```
output:
```
GribField(t,1000,20180801,1200,0,0)
GribField(u,1000,20180801,1200,0,0)
```
> Implement parts for url stream

- earthkit/data/writers/grib.py
- tests/numpy_fs/test_numpy_fs_write.py
With this PR we can specify the bits per value for the grib encoding when saving a Numpy Fieldlists into a GRIB file:
```python
ds.save("my_data.grib", bits_per_value=24)
```
By default `bits_per_value=16`.
> Add bits_per_value option when saving numpyfs grib data

- earthkit/data/sources/file.py
- tests/utils/test_parts.py
This problem only occurs in `develop` and is the side effect of the introduction of `parts` for the `file` source.
> Fix split_on option for retrievals

- earthkit/data/readers/__init__.py
- tests/readers/test_empty_file.py
With this PR `from_source` throws an exception when the input is an empty file. Previously, the result was a `TextReader`.
The consequence of this change is that when reading/downloading multiple files now it is enough to have an empty file out of many valid ones and the program fail if the exception is uncaught.
> from_source should fail when try to load empty file

- earthkit/data/core/fieldlist.py
- earthkit/data/core/metadata.py
- earthkit/data/readers/grib/codes.py
- earthkit/data/readers/grib/index/__init__.py
- earthkit/data/readers/grib/metadata.py
- earthkit/data/sources/numpy_list.py
- earthkit/data/writers/grib.py
- tests/core/test_metadata.py
- tests/grib/test_grib_output.py
- tests/numpy_fs/test_numpy_fs_metadata.py
- tests/numpy_fs/test_numpy_fs_write.py
> Allow None for bits_per_values when saving GRIB data

- docs/guide/sources.rst
- earthkit/data/sources/ecmwf_open_data.py
- tests/sources/test_ecmwf_open_data.py
This PR adds the `model` option to the `ecmwf-open-data` source and updates the documentation:
> Add model option to ecmwf-open-data source

- earthkit/data/sources/__init__.py
With this PR finding the right class for the source when using `from_source()` is a little bit faster. It avoids running `os.walk()` to check the .py files in earthkit/data/sources whenever `from_source()`  is called.
The speedup is as follows:
- 10% on MacBook (ssd)
- 15% on ECMWF HPC (lustre) 
Please note that `from_source()` was already very fast, so the overall speedup for eathkit-data scripts is negligible.
> Improve source lookup

- earthkit/data/sources/cds.py
- tests/sources/test_cds.py
Some CDS retrievals fail with Python 3.8 due to the usage of the new dict union operator `|`, which is only available in 3.9.
> Fix cds errors due to dict union operator

- earthkit/data/readers/grib/metadata.py
- earthkit/data/utils/message.py
- environment.yml
- tests/environment-unit-tests.yml
Header only GRIB message cloning was fixed in ecCodes 2.35.0. This PR re-enables it for GRIB metadata().override(). At the same time the minimum ecCodes version was raised to 2.35.0.
> Enable header only grib message cloning

- docs/guide/sources.rst
- docs/howtos.rst
- earthkit/data/mergers/__init__.py
- earthkit/data/readers/netcdf/__init__.py
- earthkit/data/readers/netcdf/fieldlist.py
- tests/netcdf/test_netcdf_concat.py
- tests/netcdf/test_netcdf_convert.py
With this PR for NetCDF we can use the `xarray_open_mfdataset_kwargs`option to specify kwargs for `xarray.open_mfdataset()` when using the `to_xarray()` method.
```python
r = ds.to_xarray(xarray_open_mfdataset_kwargs=dict(decode_cf=False, decode_times=False))
```
> Review netcdf to_xarray args

- src/earthkit/data/readers/grib/xarray.py
- src/earthkit/data/utils/kwargs.py
Fixes #379 
- removed warnings when non-default kwargs used
- use warnings.warn() when forced kwargs specified with non-default values
> Use warnings.warn for kwargs check in to_xarray

- src/earthkit/data/readers/netcdf/dataset.py
- src/earthkit/data/readers/netcdf/fieldlist.py
- tests/netcdf/test_netcdf_geography.py
This PR fixes the following NetCDF problems:
- fix issue when fields were assigned to variables without lat-lon/x-y dimensions
- fix getting the correct latitudes-longitudes when the variables "lat" and "lon" are used with the following mapping from x and y:
> Fix reading netcdf generated from FA file

- src/earthkit/data/core/order.py
- tests/core/test_remapping.py
This PR fixes the issue when repeated use of remapping with a patch lost the original remapping. Now this works as expected and in the following code r1 and r2 define the same remapping (and patches).
```python
from earthkit.data.core.order import build_remapping
remapping = {"type": "{type}{number}"}
patch = {"type": {"cf0": "x"}}
r1 = build_remapping(remapping, patch)
r2 = build_remapping(r1)
```
This PR also adds tests for using remapping and patches.
> Fix repeated use of build_remapping with a patch

- src/earthkit/data/readers/__init__.py
- src/earthkit/data/sources/ecmwf_api.py
- src/earthkit/data/sources/empty.py
- tests/sources/test_empty.py
- tests/sources/test_mars.py
This PR fixes the issue when a MARS retrieval specified `expect=any` but an exception was raised when no data was available/retrieved. With this PR now an empty fieldlist (an EmptySource object) is returned in this case.  E.g.:
```python
ds = from_source(
"mars",
expect="any",
param=["2t", "msl"],
levtype="sfc",
area=[50, -50, 20, 50],
grid=[2, 2],
date="1054-05-10",
)
assert len(ds) == 0
```
> Return empty fieldlist when expect=any used in mars and no data is available

- src/earthkit/data/core/index.py
- src/earthkit/data/readers/grib/index/sql.py
This PR removes the normalisation of metadata key names passed to:
- sel()
- isel()
- order_by()
- unique_values()
Previously the following normalisation was applied for GRIB metadata keys:
```python
@alias_argument("levelist", ["level", "levellist"])
@alias_argument("levtype", ["leveltype"])
@alias_argument("param", ["variable", "parameter"])
@alias_argument("number", ["realization", "realisation"])
@alias_argument("class", "klass")
def _normalize_kwargs_names(self, **kwargs):
return kwargs
```
> Do not normalise metadata key names for sel, isel and order_by calls

- environment.yml
- pyproject.toml
- tests/environment-unit-tests.yml
The minimum version of CDSAPI has been upgraded to 0.7.1, which includes a bugfix to ensure compatibility between the new CDS beta and earthkit-data. The optional cads-api-client dependencies have also been removed, as the minimum version of cads-api-client has been upgraded within cdsapi.
> Upgrade minimum version of cdsapi

- src/earthkit/data/core/fieldlist.py
- tests/grib/test_grib_inidces.py
This PR refactors the implementation of the `index()`and `indices()` FieldList methods. In particular, it improves the performance when `index()` is called with a key not belonging to the default index keys.
> Improve fieldlist indices implementation

- src/earthkit/data/sources/array_list.py
- tests/array_fieldlist/test_numpy_fs_metadata.py
This PR implements the repr for an ArrayField.  E.g. if `f` contains surface data:
```python
print(f)
>>> ArrayField(2t,None,20200513,1200,0,0)
```
Note: this repr is GRIB specific.
> Implement repr to ArrayField

- src/earthkit/data/indexing/cube.py
- tests/grib/test_grib_cube.py
This PR fixes the issue when the missing "number" metadata key caused a crash when generating a detailed report for a FieldCube.
> Fix cube detailed error report

- docs/guide/sources.rst
- src/earthkit/data/sources/ecmwf_api.py
- src/earthkit/data/sources/mars.py
- src/earthkit/data/testing.py
- tests/sources/test_mars.py
Fixes #454 
This PR adds the `log` option to `from_source("mars",...)` to enable logging control of the retrievals. Because the retrieval is based on either the command line (direct) MARS client or the Python `ecmwf_api` client, `log` offers different options for these different clients.
> Allow logging control for mars source

- src/earthkit/data/readers/grib/metadata.py
This allows getting the "resolution" metadata for grib with "lambert_azimuthal_equal_area" encoding.
> support lambert_azimuthal_equal_area metadata

- src/earthkit/data/readers/grib/metadata.py
- src/earthkit/data/sources/array_list.py
- tests/grib/test_grib_serialise.py
Relates to #453 
This PR adds serialisation to the following objects:
- ArrayField
- ArrayFieldlist
- StandaloneGribMetadata
- RestrictedGribMetadata
> Add serialisation to grib array fieldlist

- src/earthkit/data/sources/array_list.py
- tests/grib/test_grib_output.py
This PR adds the `handle` property to ArrayField to return the underlying GRIB handle (when exists).
> Add handle property to array field

- src/earthkit/data/readers/grib/file.py
- src/earthkit/data/readers/grib/index/__init__.py
- src/earthkit/data/readers/grib/memory.py
- src/earthkit/data/sources/stream.py
- tests/grib/test_grib_cache.py
- tests/grib/test_grib_serialise.py
Relates to #453
This PR adds serialisation to the following objects:
GRIBReader
GribMaskFieldList
GribMultiFieldList
GribFieldListInMemory
> Add serialisation to grib fieldlists

- docs/release_notes/version_0.10_updates.rst
- src/earthkit/data/readers/grib/metadata.py
- tests/grib/test_grib_metadata.py
With this PR when "param" or "shortName" in a namespace is "\~" in the GRIB header, `metadata()` returns the value of "paramId" as a str for both these keys in the relevant namespaces. Previously "~" was returned.
> Fix unknown param in grib namespaces

- src/earthkit/data/readers/__init__.py
- tests/readers/test_empty_file.py
When no file found to read from, a `FileExistsError` was being thrown,
Would `FileNotFoundError` be more apt?
> Fix: Use `FileNotFoundError` when no file found rather than FileExistsError

- docs/examples/numpy_fieldlist.ipynb
- docs/guide/misc/grib_memory.rst
- docs/guide/misc/grib_metadata.rst
- src/earthkit/data/core/fieldlist.py
- src/earthkit/data/indexing/fieldlist.py
- src/earthkit/data/readers/grib/codes.py
- src/earthkit/data/readers/grib/index/__init__.py
- src/earthkit/data/readers/grib/memory.py
- src/earthkit/data/readers/grib/metadata.py
- src/earthkit/data/sources/array_list.py
- src/earthkit/data/utils/diag.py
- tests/grib/grib_fixtures.py
- tests/grib/test_grib_cache.py
This PR:
- reduces the memory usage when a new array fieldlist is created with `FieldList.to_fieldlist()` 
- reduces the memory usage when `to_numpy()`, `to_array()` or `values` called on a fieldlist
- applies the `use-grib-metadata-cache` setting to all types of GRIB fields, even for fields entirely in memory
> Improve in memory gribfield implementation

- src/earthkit/data/core/fieldlist.py
- src/earthkit/data/core/metadata.py
- src/earthkit/data/indexing/fieldlist.py
- src/earthkit/data/readers/grib/codes.py
- src/earthkit/data/readers/grib/memory.py
- src/earthkit/data/readers/grib/metadata.py
- src/earthkit/data/readers/grib/output.py
- src/earthkit/data/readers/netcdf/field.py
- src/earthkit/data/sources/array_list.py
- src/earthkit/data/sources/forcings.py
- src/earthkit/data/utils/metadata/dict.py
- src/earthkit/data/writers/__init__.py
- src/earthkit/data/writers/grib.py
- tests/core/test_metadata.py
- tests/grib/test_grib_copy.py
This PR adds the `copy()` method to fields. The result is a new field containing:
- reference to the values/values accessor in the original field
- a wrapped metadata object updated with the kwargs
The original field is kept unaltered.
E.g. if `f` is a field with "level" = 500:
```python
>>> f_new = f.copy(level=700)
>>> f.metadata("level")
>>> f_new.metadata("level")
500
700
```
The kwargs can contain callables with the signature described below:
```python
def _func(field, key, original_metadata):
return original_metadata[key] + 100
f_new = f.copy(level=_func)
print(f.metadata("level"))
print(f_new.metadata("level"))
```
```
500
600
```
> Alter field metadata

- docs/examples/file_stream.ipynb
- docs/examples/index.rst
- docs/examples/url_stream.ipynb
- docs/guide/sources.rst
- docs/guide/streams.rst
- src/earthkit/data/readers/__init__.py
- src/earthkit/data/readers/bufr/__init__.py
- src/earthkit/data/readers/covjson.py
- src/earthkit/data/readers/directory.py
- src/earthkit/data/readers/grib/__init__.py
- src/earthkit/data/readers/grib/file.py
- src/earthkit/data/readers/grib/memory.py
- src/earthkit/data/sources/file.py
- src/earthkit/data/sources/stream.py
- src/earthkit/data/sources/url.py
- src/earthkit/data/testing.py
- src/earthkit/data/utils/stream.py
- tests/bufr/test_bufr_file_parts.py
- tests/grib/test_grib_file_stream.py
- tests/grib/test_grib_stream.py
- tests/grib/test_grib_url_stream.py
- tests/sources/test_file.py
- tests/utils/test_stream.py
This PR implements the `stream` and `read_all` options for the  "file" source for:
- single files
- multiple files
- directories
- archives
- the combination of these
The stream options can be combined with `parts`.
The PR also implements the concatenation of stream sources. E.g. the following example concatenates 3 different stream sources into a single stream:
```python
stream1 = open(earthkit_examples_file("test.grib"), "rb")
ds1 = from_source("stream", stream1)
ds2 = from_source("file", earthkit_examples_file("test4.grib"), stream=True)
ds3 = from_source("url", earthkit_remote_test_data_file("examples/test6.grib"), stream=True)
ds = ds1 + ds2 + ds3
for f in ds:
print(f)
```
> Add stream support for file source

- src/earthkit/data/readers/grib/xarray.py
- src/earthkit/data/utils/xarray/builder.py
- src/earthkit/data/utils/xarray/defaults.yaml
- src/earthkit/data/utils/xarray/engine.py
- src/earthkit/data/utils/xarray/profile.py
- tests/xr_engine/test_xr_engine.py
This PR adds the `direct_backend` option to `to_xarray()`. If True, the backend is used directly bypassing `xarray.open_dataset()` and ignoring all non-backend related kwargs. If False, the data is read via `xarray.open_dataset()`. Its default value (None) expands to False unless the `profile` overwrites it.
> Bypass open_dataset in to_xarray

- docs/guide/sources.rst
- docs/release_notes/version_0.10_updates.rst
- environment.yml
- pyproject.toml
- src/earthkit/data/sources/ads.py
- src/earthkit/data/sources/cds.py
- src/earthkit/data/sources/prompt.py
- tests/environment-unit-tests.yml
- tests/readers/test_netcdf_reader.py
- tests/sources/test_wekeocds.py
Related to #499 
This PR: 
- Fixed issue when setting up `cds` source credentials via the prompt did not work.
- Fixed issue when setting up `ads` source credentials via the prompt did not work.
- Increased `cdsapi` dependency to version 0.7.2 to be compatible with the new CDS/ADS services.
- Corrected documentation for `ads`.
Planned to be released as `0.10.9`.
> Update cds and ads prompt

- docs/guide/sources.rst
- src/earthkit/data/core/fieldlist.py
- src/earthkit/data/readers/grib/xarray.py
- tests/grib/test_grib_summary.py
- tests/xr_engine/test_xr_engine.py
This PR adds the following methods, which already exist for Fieldlists, to Fields:
- to_xarray()
- ls()
- describe()
> Add more fieldlist methods to fields

- src/earthkit/data/readers/grib/xarray.py
- src/earthkit/data/utils/xarray/builder.py
- src/earthkit/data/utils/xarray/coord.py
- src/earthkit/data/utils/xarray/defaults.yaml
- src/earthkit/data/utils/xarray/engine.py
- src/earthkit/data/utils/xarray/fieldlist.py
- src/earthkit/data/utils/xarray/profile.py
- src/earthkit/data/utils/xarray/splitter.py
- tests/xr_engine/test_xr_engine.py
This PR adds the `add_earthkit_attrs` kwarg to `to_xarray()`.
```rst
* add_earthkit_attrs: bool, None
If True, add earthkit specific attributes to the dataset. Its default value
(None) expands to True unless the ``profile`` overwrites it.
```
> Make earthkit attributes optional in Xarray engine

- src/earthkit/data/utils/message.py
- tests/sources/test_mars.py
This PR prevents eccodes from printing to LOG.error when `eccodes.codes_set_key_vals()` is called with an empty dictionary.
Originally this error message was generated:
```
gribapi.errors.InvalidKeyValueError: Empty key/values argument
Failed to set metadata at once: Empty key/values argument
```
> Prevent calling eccodes.codes_set_key_vals with an empty dict

- src/earthkit/data/core/fieldlist.py
- tests/ai-models/test_ai_warpped_field.py
Fixes https://github.com/ecmwf-lab/ai-models/issues/63
Note: the code in ai-models `src/ai_models/inputs/transform.py` should be removed and the `Field.clone()` method should be used instead.
> Fix failing to_numpy() call on a wrapped field

- src/earthkit/data/sources/ecfs.py
- src/earthkit/data/sources/url.py
Works with
```
ekd.from_source('ecfs', '/path/to/data')
```
and
```
ekd.from_source('url', 'ec:/path/to/data')
```
> Add ecfs source

- src/earthkit/data/readers/grib/__init__.py
- src/earthkit/data/utils/xarray/engine.py
- tests/readers/test_geotiff_reader.py
> Only use Xarray earthkit backend for GRIB data

- src/earthkit/data/readers/grib/xarray.py
- src/earthkit/data/utils/xarray/attrs.py
- src/earthkit/data/utils/xarray/cf_attrs.yaml
- src/earthkit/data/utils/xarray/engine.py
- tests/xr_engine/test_xr_engine.py
> No units attribute for single variable in xarray engine

- src/earthkit/data/readers/grib/output.py
- tests/grib/test_grib_output.py
Earthkit data currently allows specifying an output file name template such as `"output/{date}-{time}-{step}.grib2"`. In some cases, users might want to add some format specifiers, for instance zero-padding for the `step` value, like so: `"output/{date}-{time}-{step:03}.grib2"`. 
After the regex groups are extracted from the template string, split them with `:` and take the first element to get the values from the handles.
> feat: support string format specification for output file path template

- src/earthkit/data/__init__.py
Add `.utils.array` as `array_api` to top level.
```python
from earthkit.data import array_api
an = array_api.get_backend(mask).module
```
Will allow for easier utilisation of the array api backends.
> Add array_api to top level

- src/earthkit/data/utils/patterns.py
- tests/utils/test_patterns.py
Suggestion for a new pattern type to support passing a date with a timedelta. The syntax would look as the following.
```py
Pattern("/path/to/data/{date:strftimedelta(-6h;%Y%m%d)}{date:strftimedelta(-6h;%H)}_006")
```
Would allow an easier selection of data at validity time in forecast files.
> feat: add strftimedelta pattern

- docs/examples/geotiff.ipynb
- src/earthkit/data/encoders/__init__.py
- src/earthkit/data/encoders/geotiff.py
- src/earthkit/data/readers/geotiff.py
Setting `band_as_variable` and `mask_and_scale` to `True` everywhere by default aligns better with what users likely expect as good defaults in most cases and should avoid some pitfalls in data format conversion. For now, this behaviour is documented in the example in the docs.
> Add GeoTIFF encoder and tweak default kwargs when opening

- docs/release_notes/version_0.13_updates.rst
- src/earthkit/data/indexing/fieldlist.py
- src/earthkit/data/readers/grib/memory.py
- src/earthkit/data/sources/stream.py
Fixes the `test_fdb` case reported in  #646.
> Fix GRIB data reading from FDB streams in multiprocessing

- docs/release_notes/version_0.13_updates.rst
- src/earthkit/data/readers/grib/index/__init__.py
- tests/xr_engine/test_xr_chunks.py
This PR fixes the following issue:
Assume the input grib contains a large number or large fields and we want to use chunking (dask) to process it as an xarray. Then the following computation crashes due to a multithreading problem:
```python
ds_in = from_source("file", "t2.grib")
ds = ds_in.to_xarray(time_dim_mode="valid_time", chunks="auto")
avg = ds["2t"].mean("valid_time").load()
```
> Fix crash when chunks used in Xarray created from GRIB data

- docs/examples/files.ipynb
- docs/release_notes/version_0.14_updates.rst
- src/earthkit/data/sources/file_pattern.py
- tests/sources/test_file_pattern.py
This PR fixes the issue when the `file-pattern` source used with the ``hive_partitioning=False`` option did not return the expected data object (e.g. for GRIB data did not return a FieldList).
> The file-pattern source does not return the expected object

- src/earthkit/data/indexing/fieldlist.py
- src/earthkit/data/utils/metadata/dict.py
- src/earthkit/data/utils/xarray/builder.py
- src/earthkit/data/utils/xarray/grid.py
- tests/xr_engine/test_xr_lod.py
With this PR the examples below work:
```python
import earthkit.data as ekd
prototype = {
"latitudes": [10.0, 0.0, -10.0],
"longitudes": [20, 40.0],
"values": [1, 2, 3, 4, 5, 6],
"valid_datetime": "2018-08-01T09:00:00Z",
}
d = [
{"param": "t", "level": 500, **prototype},
{"param": "t", "level": 850, **prototype},
{"param": "u", "level": 500, **prototype},
{"param": "u", "level": 850, **prototype},
]
ds = ekd.from_source("list-of-dicts", d)
a = ds.to_xarray()
```
```python
import earthkit.data as ekd
prototype = {
"values": [1, 2, 3, 4, 5, 6],
"valid_datetime": "2018-08-01T09:00:00Z",
}
d = [
{"param": "t", "level": 500, **prototype},
{"param": "t", "level": 850, **prototype},
{"param": "u", "level": 500, **prototype},
{"param": "u", "level": 850, **prototype},
]
ds = …
```
> Enable converting fields with UserMetadata into Xarray

- docs/release_notes/version_0.14_updates.rst
- src/earthkit/data/readers/grib/codes.py
- tests/grib/test_grib_metadata.py
With ecCodes 2.41.0 when we get the `gridSpec` key with a `default` value an exception not caught in the high-level ecCodes Python API is raised.
```
ds[0].metadata("gridSpec", default=None)
...
... python3.11/site-packages/eccodes/highlevel/message.py:68: in get
return self._get(name, ktype=ktype)
gribapi.errors.FunctionNotImplementedError: Function not yet implemented
```
This PR provides a fix for it in the earthkit-data GRIB interface ensuring that:
```python
ds[0].metadata("gridSpec", default=None)
```
works with all ecCodes versions.
> Fix crash when getting gridSpec GRIB metadata key

- docs/examples/xarray_engine_mono_variable.ipynb
- docs/release_notes/version_0.16_updates.rst
- src/earthkit/data/readers/grib/xarray.py
- src/earthkit/data/utils/xarray/engine.py
- src/earthkit/data/utils/xarray/profile.py
- tests/xr_engine/test_xr_ens.py
Rename the `fill` option (added in #738) to `fill_metadata` in `to_xarray()`
> Rename fill to fill_metadata in to_xarray

- docs/guide/config.rst
Fixes a typo in the [Environment variables section of the config tutorial](https://earthkit-data.readthedocs.io/en/latest/guide/config.html#config-env), which references `EARTHKIT_REGRID_URL_DOWNLOAD_TIMEOUT` instead of `EARTHKIT_DATA_URL_DOWNLOAD_TIMEOUT`. I went through the example with both variants and got the desired result only with the change.
* I have run all existing tests and confirmed …
> Use correct environment variable name in doc

- .github/ci-hpc-gpu-config.yml
- .github/workflows/nightly-hpc-gpu.yml
The tests will run each night, and can also be triggered manually if desired. Perhaps the pytest command will need to be modified in order to enable gpu-based mechanisms - edit .github/ci-hpc-gpu-config.yml in order to do this.
> Run nightly tests on gpu-enabled hpc nodes

- src/earthkit/data/utils/patterns.py
Fix SyntaxWarning
```
/earthkit/data/utils/patterns.py:672: SyntaxWarning: invalid escape sequence '\S'
t += f"(?P<{p.name}>\S+)"
```
> Fix syntax warning in patterns

- src/earthkit/data/utils/xarray/coord.py
- src/earthkit/data/utils/xarray/defaults.yaml
Fixed issue when the attributes were not added to some coordinates (e.g. step) when Xarray generated with the Xarray engine.
> Fix missing coordinate attributes in generated Xarray

- src/earthkit/data/utils/xarray/builder.py
- tests/xr_engine/test_xr_attrs.py
Fixes the issue #786.
A relevant test added.
> Fix for the issue #786: inconsistent behaviour of global_attrs in to_xarray

- src/earthkit/data/utils/xarray/fieldlist.py
- tests/xr_engine/test_xr_remapping.py
This PR fixes the following bug in the xarray engine:
```
import earthkit.data as ekd
fl = ekd.from_source('sample', 'test.grib')
ds = fl.to_xarray(remapping={"param": "{param}_{levtype}"}, lazy_load=False)
print(ds)
```
results with
```
<xarray.Dataset> Size: 240B
Dimensions:    (latitude: 11, longitude: 19)
Coordinates:
* latitude   (latitude) float64 88B 73.0 69.0 65.0 61.0 ... 41.0 37.0 33.0
* longitude  (longitude) float64 152B -27.0 -23.0 -19.0 ... 37.0 41.0 45.0
Data variables:
*empty*
Attributes:
Conventions:  CF-1.8
institution:  ECMWF
```
i.e. no variables present in the dataset, while the result should be
```
<xarray.Dataset> Size: 4kB
Dimensions:    (latitude: 11, longitude: 19)
Coordinates:
* latitude   (latitude) float64 88B 73.0 69.0 65.0 61.0 ... 41.0 37.0 33.0
* longitude …
```
> Fix xr-engine remapping when lazy_load=False

- src/earthkit/data/readers/__init__.py
- src/earthkit/data/readers/directory.py
- src/earthkit/data/readers/grib/file.py
Adding the attribute `_source_kwargs` to `Reader` class (PR #791) caused a regression, as demonstrated by the test `test_netcdf_opendap`.
This PR fixes the problem by moving the attribute to those subclasses of `Reader` where it is actually needed, that is `GRIBReader` and `DirectoryReader`.
> Fix of a regression caused by PR #791

- src/earthkit/data/core/fieldlist.py
- src/earthkit/data/indexing/tensor.py
- src/earthkit/data/utils/xarray/builder.py
- tests/xr_engine/test_xr_slice.py
- tests/xr_engine/test_xr_tensor.py
This PR fixes a problem in handling empty slices of Xarray objects whenever the underlying data in managed by a field list through a `FieldListTensor` object (e.g. when a GRIB file is converted to Xarray via `.to_xarray(lazy_load=True, ...)` method). Consider the following code:
```python3
from earthkit.data import from_source
from earthkit.data.testing import earthkit_remote_test_data_file
ds_ek = from_source("url", earthkit_remote_test_data_file("xr_engine/level/pl.grib"))
ds = ds_ek.to_xarray(lazy_load=True)
ds2 = ds.sel(level=slice(350, 360))  # in ds2, the level-dim has size 0
ds2.load()  # crashes
ds3 = ds.load().sel(level=slice(350, 360))   # this works, because the full ds is loaded into memory 
```
The problem with `ds2.load()` comes from the fact that the underlying field list …
> Fix handling empty slices of a tensor

- environment.yml
- pyproject.toml
- src/earthkit/data/core/fieldlist.py
- src/earthkit/data/decorators.py
- src/earthkit/data/readers/geotiff.py
- src/earthkit/data/readers/grib/codes.py
- src/earthkit/data/readers/grib/metadata.py
- src/earthkit/data/readers/grib/virtual.py
- src/earthkit/data/readers/netcdf/field.py
- src/earthkit/data/readers/netcdf/fieldlist.py
- src/earthkit/data/sources/cds.py
- src/earthkit/data/sources/forcings.py
- src/earthkit/data/sources/stream.py
- src/earthkit/data/utils/metadata/dict.py
- src/earthkit/data/utils/patterns.py
- src/earthkit/data/utils/request.py
- src/earthkit/data/utils/xarray/attrs.py
- src/earthkit/data/utils/xarray/profile.py
- tests/environment-unit-tests.yml
- tests/thread/test_thread_cached_property.py
This PR replaces the usage of `functools.cached_property` with a custom thread safe implementation: `earthkit.data.decorators.cached_property`. This was a necessary step since the thread safety in `functools.cached_property` was removed in Python 3.12.
> Use thread safe cached property

- src/earthkit/data/readers/grib/virtual.py
- tests/lazy/test_lazy_fdb.py
Fixed issue when fields loaded from FDB lazily returned incorrect `step_timedelta` metadata.
> Fix lazy fdb fields return incorrect step_timedelta
