- .github/workflows/notify_ci.yml
- .github/workflows/on-push.yml
So we can access the secret webhook even from PRs created from public forks.
> Split CI Teams notification into separate workflow

- Makefile
Feel free to merge or ignore if you think this won't help anyone. It would have helped me personally as a visitor to this repo!
> Add `make setup` to help devs setup their local env

- docs/examples.rst
- docs/examples/cds.ipynb
- docs/examples/mars.ipynb
- earthkit/data/sources/cds.py
- environment.yml
- tests/documentation/test_notebooks.py
- tests/sources/test_cds.py
> Add cds access as a source type

- tests/grib/test_grib_contents.py
> Add test for missing grib metadata

- setup.cfg
> Fix pip install

- earthkit/data/readers/grib/codes.py
- tests/grib/test_grib_contents.py
> Remove unused proj string methods from grib field

- earthkit/data/readers/bufr.py
- tests/bufr/test_bufr_convert.py
> to_pandas fails for bufr when no filters specified

- earthkit/data/readers/grib/codes.py
- earthkit/data/readers/grib/fieldlist.py
- tests/grib/test_grib_contents.py
> Add projection method to fieldlist

- docs/examples.rst
- docs/examples/ecmwf_open_data.ipynb
- docs/guide/sources.rst
- earthkit/data/sources/ecmwf_open_data.py
- earthkit/data/testing.py
- environment.yml
- setup.cfg
- tests/environment-unit-tests.yml
- tests/sources/test_ecmwf_open_data.py
The PR adds a new source "ecmwf-open-data" to retrieve ECMWF open data.
> Add ecmwf opendata source

- docs/api.rst
- docs/conf.py
- docs/guide/data.rst
- docs/guide/data_format/bufr.rst
- docs/guide/data_format/grib.rst
- docs/skip_api_rules.py
- earthkit/data/core/index.py
- earthkit/data/readers/bufr/bufr.py
- earthkit/data/readers/bufr/pandas.py
- earthkit/data/utils/summary.py
- tests/bufr/test_bufr_contents.py
- tests/bufr/test_bufr_order_by.py
- tests/bufr/test_bufr_sel.py
Add more BUFR documentation and tests
> Improve BUFR documentation and tests

- Makefile
- earthkit/data/arguments/input_manager.py
- earthkit/data/core/caching.py
- earthkit/data/core/settings.py
- earthkit/data/sources/file.py
- environment.yml
- pytest.ini
- setup.cfg
- tests/conftest.py
- tests/core/test_cache.py
- tests/environment-unit-tests.yml
> Caching initialisation hangs when log level is debug

- earthkit/data/core/fieldlist.py
- tests/sources/test_numpy_list.py
We can call it like this:
```python
ds.save("my_path", append=True)
```
> Add append option to save method on fieldlists

- earthkit/data/sources/cds.py
- tests/sources/test_cds.py
> Fix split_on with multiple request parameters

- earthkit/data/sources/cds.py
- tests/sources/test_cds.py
> Improve cds tests

- earthkit/data/readers/grib/xarray.py
- tests/grib/test_grib_convert.py
> Fix crash in to_xarray when filter_by_keys is used

- earthkit/data/readers/grib/output.py
- tests/grib/test_grib_output.py
> Fix setting grib levtype test

- earthkit/data/readers/netcdf.py
- tests/netcdf/test_netcdf_fieldlist.py
> Allow string coordinates in netcdf

- earthkit/data/readers/shapefile.py
- earthkit/data/readers/unknown.py
- earthkit/data/utils/bbox.py
- tests/readers/test_shapefile_reader.py
- tests/utils/test_bbox.py
> Add shapefile support

- earthkit/data/readers/netcdf.py
- tests/netcdf/test_netcdf_fieldlist.py
> Avoid crash in netcdf field parsing when bounds is not a str

- earthkit/data/core/__init__.py
- earthkit/data/core/caching.py
- earthkit/data/core/fieldlist.py
- earthkit/data/core/index.py
- earthkit/data/indexing/database/sql.py
- earthkit/data/readers/archive.py
- earthkit/data/readers/grib/index/__init__.py
- earthkit/data/readers/grib/index/db.py
- earthkit/data/sources/ecmwf_api.py
- earthkit/data/sources/multi.py
- earthkit/data/sources/url.py
- earthkit/data/sources/virtual_directory.py
- earthkit/data/sources/wekeo.py
- earthkit/data/sources/wekeocds.py
- earthkit/data/utils/__init__.py
- earthkit/data/utils/progbar.py
- environment.yml
- setup.cfg
- tests/downstream-ci-requirements.txt
- tests/environment-unit-tests.yml
With this PR less modules are imported when we call:
```python
import earthkit.data
```
> Improve initial import

- src/earthkit/data/readers/netcdf/coords.py
- src/earthkit/data/readers/netcdf/fieldlist.py
- tests/netcdf/test_netcdf_fieldlist.py
> Fix netcdf with time coordinate containing cftime

- docs/release_notes/version_0.9_updates.rst
> Release 0.9.3

- src/earthkit/data/core/__init__.py
This PR sets the default value of `progress_bar` to False in `unique_values()`.
> Set progress_bar default to False for unique_values

- .gitignore
- docs/examples/fdb.ipynb
- docs/examples/grib_fdb_write.ipynb
- docs/guide/sources.rst
- src/earthkit/data/sources/fdb.py
- src/earthkit/data/testing.py
- tests/data/fdb_schema.txt
- tests/sources/test_fdb.py
This PR adds the`config` and `userconfig` options to the `fdb` source. These are directly passed to `pyfdb.FDB()`.
> Add config option to fdb source

- src/earthkit/data/mergers/__init__.py
- src/earthkit/data/readers/netcdf/__init__.py
- src/earthkit/data/readers/netcdf/field.py
- tests/netcdf/test_netcdf_geography.py
- tests/netcdf/test_netcdf_output.py
- tests/readers/test_netcdf_reader.py
> Fix netcdf fieldlist implementation

- src/earthkit/data/testing.py
- src/earthkit/data/utils/array.py
- tests/utils/test_array.py
Add support for jax as a backend
> Add jax backend

- docs/examples/index.rst
- docs/examples/settings.ipynb
- docs/examples/settings_env_vars.ipynb
- docs/guide/settings.rst
- src/earthkit/data/core/settings.py
- src/earthkit/data/sphinxext/generate_settings_env_rst.py
- tests/core/test_settings.py
> Enable using environment variables for settings

- docs/release_notes/version_0.12_updates.rst
- src/earthkit/data/core/index.py
- tests/grib/test_grib_concat.py
> Fix max recursion depth exceeded when concatenate

- docs/release_notes/version_0.12_updates.rst
- src/earthkit/data/__init__.py
> Made Field available as a top level import

- docs/release_notes/version_0.13_updates.rst
- src/earthkit/data/readers/directory.py
- src/earthkit/data/testing.py
- tests/sources/test_file.py
> Could not convert ZIP containing a single NetCDF file to Xarray

- src/earthkit/data/readers/netcdf/dataset.py
- src/earthkit/data/readers/netcdf/field.py
- src/earthkit/data/readers/netcdf/fieldlist.py
- tests/netcdf/test_netcdf_geography.py
- tests/netcdf/test_netcdf_metadata.py
This PR fixes the issue when NetCDF data with the following structure was not parsed into a fieldlist when read with `from_source()`.
> NetCDF with 1D lat-lon cannot be parsed into fieldlist

- src/earthkit/data/readers/grib/xarray.py
- tests/xr_engine/test_xr_engine.py
> Do not modifiy xarray engine kwargs dicts in place

- pyproject.toml
Enables using ecmwfapirc for authentication
> build: update polytope-client

- docs/guide/config.rst
> Use correct environment variable name

- docs/release_notes/version_0.16_updates.rst
- environment.yml
- pyproject.toml
- tests/environment-unit-tests.yml
> Merge 0.16.1 into develop

- docs/release_notes/version_0.16_updates.rst
- src/earthkit/data/utils/xarray/builder.py
- tests/xr_engine/test_xr_attrs.py
> Feature/merge 0.16.2 into develop

- docs/release_notes/version_0.16_updates.rst
- src/earthkit/data/readers/__init__.py
- src/earthkit/data/readers/directory.py
- src/earthkit/data/readers/grib/file.py
- src/earthkit/data/utils/xarray/fieldlist.py
- tests/xr_engine/test_xr_remapping.py
> Merge 0.16.4 into develop

- docs/release_notes/version_0.16_updates.rst
> Update release notes 0.16.5

- docs/release_notes/version_0.16_updates.rst
- src/earthkit/data/core/caching.py
- src/earthkit/data/utils/progbar.py
- tests/thread/test_thread_url_cache_off.py
This PR:
- fixes #801 
- makes the progbar work when downloading data in mutiple threads
> Fix crash when downloading data in multiple threads

- docs/release_notes/version_0.16_updates.rst
- src/earthkit/data/readers/grib/codes.py
- tests/grib/test_grib_serialise.py
> Merge 0.16 7.into develop
